const PREFIX = "TO_DO_APP_"
export const REFRESH_TOKEN = `${PREFIX}REFRESH_TOKEN`
export const TOKEN = `${PREFIX}TOKEN`
export const LAST_REFRESH_TOKEN_TIMESTAMP = `${PREFIX}LAST_REFRESH_TOKEN_TIMESTAMP`
export const IS_AUTH = `${PREFIX}IS_AUTH`
export const TOKEN_EXPIRES_TIME = `${PREFIX}TOKEN_EXPIRES_TIME`